# grafana/provisioning/datasources/opensearch-datasource.yaml
apiVersion: 1

apiVersion: 1
datasources:
- name: OpenSearch
  type: opensearch
  access: proxy
  url: http://opensearch:9200
  jsonData:
    timeField: timestamp
    version: "2.12.0"
    tlsAuth: false
    tlsAuthWithCACert: false
