# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

name: Check License Header

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run License Header Check
        run: |
          set -e  # Stop script on errors to prevent silent failures
          
          missing_license_files=$(grep -rcL --exclude-dir={.git,build,**vernemq**} \
            --exclude=\*.{crt,key,pem,zed,hcl,md,json,csv,mod,sum,tmpl,args} \
            --exclude={CODEOWNERS,LICENSE,MAINTAINERS} \
            --regexp "Copyright (c) Abstract Machines" .)
          
          if [ -n "$missing_license_files" ]; then
            echo "License header check failed. The following files are missing the license header:"
            echo "$missing_license_files"
            exit 1
          else
            echo "All files have the appropriate license headers."
          fi
