# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

name: Check License Header

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check License Header
        run: |
          CHECK=""
          for file in $(find . -type f ! -path "./.git/*" ! -path "./build/*" ! -path "./**vernemq**/*" \
            ! -name "*.crt" ! -name "*.key" ! -name "*.pem" ! -name "*.zed" ! -name "*.hcl" \
            ! -name "*.md" ! -name "*.json" ! -name "*.csv" ! -name "*.mod" ! -name "*.sum" \
            ! -name "*.tmpl" ! -name "*.args" ! -name "CODEOWNERS" ! -name "LICENSE" ! -name "MAINTAINERS"); do
              
              if ! head -n 3 "$file" | grep -q "Copyright (c) Abstract Machines"; then
                CHECK="$CHECK $file"
              fi
          done

          if [ "$CHECK" ]; then
            echo "License header check failed. Fix the following files:"
            echo "$CHECK"
            exit 1
          fi
